// Mock data for Cora platform — used in development until backend is connected

export const mockTherapists = [
  {
    id: 'psy_001',
    firstName: 'Carlos',
    lastName: 'Rodríguez Vargas',
    avatar: null,
    title: 'Psicólogo Clínico',
    specializations: ['Ansiedad', 'Depresión', 'Terapia Cognitivo-Conductual', 'Estrés'],
    languages: ['Español', 'Inglés'],
    experience: 12,
    rating: 4.9,
    reviewCount: 127,
    bio: 'Especialista en terapia cognitivo-conductual con más de 12 años de experiencia. Trabajo principalmente con personas que enfrentan ansiedad, depresión y estrés laboral. Mi enfoque se centra en proporcionar un espacio seguro y sin juicios donde puedas explorar tus emociones y desarrollar herramientas prácticas para mejorar tu bienestar.',
    license: 'CPC-2024-1234',
    verified: true,
    sessionPrice: 65,
    currency: 'USD',
    availability: {
      monday: ['09:00', '10:00', '11:00', '15:00', '16:00', '17:00'],
      wednesday: ['09:00', '10:00', '11:00', '15:00', '16:00'],
      friday: ['09:00', '10:00', '14:00', '15:00'],
    },
    nextAvailable: '2026-04-10T09:00:00Z',
    acceptingNewPatients: true,
    sessionTypes: ['video', 'audio', 'chat'],
    approach: 'Cognitivo-Conductual (TCC)',
    education: 'Doctorado en Psicología Clínica, UCR',
  },
  {
    id: 'psy_002',
    firstName: 'Ana',
    lastName: 'Mora Jiménez',
    avatar: null,
    title: 'Psicóloga y Terapeuta de Pareja',
    specializations: ['Terapia de Pareja', 'Relaciones', 'Autoestima', 'Trauma'],
    languages: ['Español'],
    experience: 8,
    rating: 4.8,
    reviewCount: 89,
    bio: 'Psicóloga especializada en terapia de pareja y relaciones. Con 8 años de experiencia, he ayudado a cientos de parejas y personas a encontrar el equilibrio emocional y construir relaciones más saludables. Creo firmemente en la capacidad de cada persona para crecer y transformarse.',
    license: 'CPC-2023-5678',
    verified: true,
    sessionPrice: 60,
    currency: 'USD',
    availability: {
      tuesday: ['10:00', '11:00', '14:00', '15:00', '16:00'],
      thursday: ['10:00', '11:00', '14:00', '15:00'],
      saturday: ['09:00', '10:00', '11:00'],
    },
    nextAvailable: '2026-04-11T10:00:00Z',
    acceptingNewPatients: true,
    sessionTypes: ['video', 'chat'],
    approach: 'Sistémica y Gestalt',
    education: 'Maestría en Psicología Clínica, UNA',
  },
  {
    id: 'psy_003',
    firstName: 'Roberto',
    lastName: 'Solano Brenes',
    avatar: null,
    title: 'Psicólogo Infanto-Juvenil',
    specializations: ['Adolescentes', 'TDAH', 'Bullying', 'Familia'],
    languages: ['Español', 'Inglés', 'Portugués'],
    experience: 15,
    rating: 4.7,
    reviewCount: 203,
    bio: 'Con 15 años trabajando con niños, adolescentes y familias. Especialista en TDAH, problemas de conducta, bullying y transiciones de vida. Mi metodología combina técnicas basadas en evidencia con un enfoque humanista que considera el contexto familiar y social del paciente.',
    license: 'CPC-2022-9012',
    verified: true,
    sessionPrice: 70,
    currency: 'USD',
    availability: {
      monday: ['14:00', '15:00', '16:00', '17:00'],
      wednesday: ['14:00', '15:00', '16:00', '17:00'],
      thursday: ['09:00', '10:00', '11:00'],
    },
    nextAvailable: '2026-04-10T14:00:00Z',
    acceptingNewPatients: true,
    sessionTypes: ['video', 'audio'],
    approach: 'Cognitivo-Conductual + Sistémico',
    education: 'Doctorado en Psicología Infanto-Juvenil, UNED',
  },
  {
    id: 'psy_004',
    firstName: 'María',
    lastName: 'Quesada Aguilar',
    avatar: null,
    title: 'Psicóloga — Mindfulness y Bienestar',
    specializations: ['Mindfulness', 'Burnout', 'Duelo', 'Ansiedad'],
    languages: ['Español', 'Inglés'],
    experience: 6,
    rating: 4.9,
    reviewCount: 64,
    bio: 'Psicóloga certificada en Mindfulness-Based Cognitive Therapy (MBCT) y Terapia de Aceptación y Compromiso (ACT). Me especializo en ayudar a personas que experimentan burnout, ansiedad crónica y procesos de duelo. Creo en un enfoque integral que une la mente, el cuerpo y las emociones.',
    license: 'CPC-2024-3456',
    verified: true,
    sessionPrice: 55,
    currency: 'USD',
    availability: {
      monday: ['08:00', '09:00', '10:00'],
      tuesday: ['08:00', '09:00', '10:00'],
      thursday: ['08:00', '09:00', '10:00'],
      friday: ['08:00', '09:00', '10:00'],
    },
    nextAvailable: '2026-04-10T08:00:00Z',
    acceptingNewPatients: true,
    sessionTypes: ['video', 'audio', 'chat'],
    approach: 'Mindfulness + ACT',
    education: 'Maestría en Neuropsicología, UCR',
  },
]

export const mockPatient = {
  id: 'usr_patient_001',
  email: 'maria.gonzalez@email.com',
  firstName: 'María',
  lastName: 'González',
  role: 'patient',
  avatar: null,
  profileComplete: true,
  createdAt: '2026-01-15T10:00:00Z',
  subscription: {
    plan: 'standard',
    status: 'active',
    price: 70,
    currency: 'USD',
    billingPeriod: 'weekly',
    nextBillingDate: '2026-04-14T00:00:00Z',
    features: ['Mensajería ilimitada', '1 sesión/semana', 'Cambio gratis de terapeuta'],
  },
  assignedTherapist: mockTherapists[0],
}

export const mockTherapistUser = {
  id: 'psy_001',
  email: 'c.rodriguez@email.com',
  firstName: 'Carlos',
  lastName: 'Rodríguez',
  role: 'psychologist',
  avatar: null,
  verified: true,
  totalPatients: 24,
  activePatients: 18,
  pendingMessages: 5,
  monthlyEarnings: 2340,
  rating: 4.9,
}

export const mockAppointments = [
  {
    id: 'apt_001',
    psychologist: mockTherapists[0],
    patient: { id: 'usr_patient_001', firstName: 'María', lastName: 'González' },
    scheduledAt: '2026-04-10T15:00:00Z',
    duration: 50,
    status: 'scheduled',
    type: 'video',
    roomId: 'room_abc123',
    meetingUrl: '/session/room_abc123',
  },
  {
    id: 'apt_002',
    psychologist: mockTherapists[0],
    patient: { id: 'usr_patient_001', firstName: 'María', lastName: 'González' },
    scheduledAt: '2026-04-03T15:00:00Z',
    duration: 50,
    status: 'completed',
    type: 'video',
    hasReview: true,
  },
  {
    id: 'apt_003',
    psychologist: mockTherapists[0],
    patient: { id: 'usr_patient_001', firstName: 'María', lastName: 'González' },
    scheduledAt: '2026-03-27T15:00:00Z',
    duration: 50,
    status: 'completed',
    type: 'video',
    hasReview: false,
  },
  {
    id: 'apt_004',
    psychologist: mockTherapists[0],
    patient: { id: 'usr_patient_002', firstName: 'José', lastName: 'Pérez' },
    scheduledAt: '2026-04-10T10:00:00Z',
    duration: 50,
    status: 'scheduled',
    type: 'chat',
  },
  {
    id: 'apt_005',
    psychologist: mockTherapists[0],
    patient: { id: 'usr_patient_003', firstName: 'Laura', lastName: 'Soto' },
    scheduledAt: '2026-04-11T14:00:00Z',
    duration: 50,
    status: 'scheduled',
    type: 'audio',
  },
]

export const mockReviews = [
  {
    id: 'rev_001',
    psychologistId: 'psy_001',
    patient: { firstName: 'María', avatar: null },
    rating: 5,
    title: 'Excelente profesional',
    content: 'El Dr. Rodríguez es increíblemente empático y profesional. Después de solo 3 sesiones ya siento una diferencia enorme en cómo manejo mi ansiedad. Lo recomiendo totalmente.',
    recommend: true,
    createdAt: '2026-04-04T10:00:00Z',
    isAnonymous: false,
  },
  {
    id: 'rev_002',
    psychologistId: 'psy_001',
    patient: { firstName: 'Carlos', avatar: null },
    rating: 5,
    title: 'Cambió mi vida',
    content: 'Llegué en un momento muy difícil y gracias al apoyo del Dr. Rodríguez pude salir adelante. Su metodología es clara y efectiva. Muy agradecido.',
    recommend: true,
    createdAt: '2026-03-28T15:00:00Z',
    isAnonymous: false,
  },
  {
    id: 'rev_003',
    psychologistId: 'psy_001',
    patient: { firstName: 'Usuario', avatar: null },
    rating: 4,
    title: 'Muy buena experiencia',
    content: 'La terapia online superó mis expectativas. La plataforma es fácil de usar y el terapeuta muy profesional.',
    recommend: true,
    createdAt: '2026-03-20T11:00:00Z',
    isAnonymous: true,
  },
]

export const mockPosts = [
  {
    id: 'post_001',
    author: { id: 'usr_001', firstName: 'María', avatar: null, role: 'patient' },
    title: 'Mi primera sesión de terapia online — lo que nadie te dice',
    content: 'Cuando decidí buscar ayuda psicológica, tenía mil dudas sobre la terapia online. ¿Sería igual de efectiva? ¿Se perdería algo sin estar físicamente presente? Quiero compartir mi experiencia después de 3 meses para que otros puedan tomar una decisión informada...',
    category: 'experiences',
    tags: ['terapia-online', 'primera-vez', 'ansiedad'],
    likeCount: 47,
    commentCount: 12,
    isLiked: false,
    createdAt: '2026-04-05T10:00:00Z',
    readTime: 5,
  },
  {
    id: 'post_002',
    author: { id: 'psy_001', firstName: 'Dr. Rodríguez', avatar: null, role: 'psychologist' },
    title: '5 técnicas de respiración para manejar ataques de ansiedad',
    content: 'La ansiedad es una de las condiciones de salud mental más comunes, y saber cómo manejarla en el momento puede marcar una gran diferencia. Hoy quiero compartirles técnicas respaldadas por la ciencia que pueden practicar en cualquier momento...',
    category: 'resources',
    tags: ['ansiedad', 'técnicas', 'respiración', 'mindfulness'],
    likeCount: 89,
    commentCount: 23,
    isLiked: true,
    createdAt: '2026-04-03T14:00:00Z',
    readTime: 7,
  },
  {
    id: 'post_003',
    author: { id: 'usr_002', firstName: 'Anónimo', avatar: null, role: 'patient' },
    title: '¿Cómo saber si necesitás terapia?',
    content: 'Muchas veces nos preguntamos si lo que estamos sintiendo "es suficientemente grave" para buscar ayuda. Quiero compartir las señales que yo ignoré por mucho tiempo antes de finalmente pedir ayuda...',
    category: 'questions',
    tags: ['salud-mental', 'autoconocimiento'],
    likeCount: 134,
    commentCount: 31,
    isLiked: false,
    createdAt: '2026-04-01T09:00:00Z',
    readTime: 4,
  },
  {
    id: 'post_004',
    author: { id: 'psy_002', firstName: 'Dra. Mora', avatar: null, role: 'psychologist' },
    title: 'Comunicación no violenta en la pareja: guía práctica',
    content: 'La forma en que nos comunicamos con nuestra pareja puede fortalecer o debilitar la relación. La Comunicación No Violenta (CNV) es una metodología que nos ayuda a expresar lo que sentimos sin atacar al otro...',
    category: 'resources',
    tags: ['pareja', 'comunicación', 'relaciones'],
    likeCount: 67,
    commentCount: 18,
    isLiked: false,
    createdAt: '2026-03-30T11:00:00Z',
    readTime: 8,
  },
]

export const mockPayments = [
  {
    id: 'pay_001',
    date: '2026-04-03T15:00:00Z',
    description: 'Sesión de terapia — Dr. Rodríguez',
    amount: 65,
    currency: 'USD',
    status: 'succeeded',
    method: 'Visa **** 4242',
  },
  {
    id: 'pay_002',
    date: '2026-03-27T15:00:00Z',
    description: 'Sesión de terapia — Dr. Rodríguez',
    amount: 65,
    currency: 'USD',
    status: 'succeeded',
    method: 'Visa **** 4242',
  },
  {
    id: 'pay_003',
    date: '2026-03-20T15:00:00Z',
    description: 'Sesión de terapia — Dr. Rodríguez',
    amount: 65,
    currency: 'USD',
    status: 'succeeded',
    method: 'Visa **** 4242',
  },
]

export const mockMessages = [
  {
    id: 'msg_001',
    from: 'Dr. Carlos Rodríguez',
    fromId: 'psy_001',
    preview: 'Hola María, ¿cómo te fue con los ejercicios de respiración que practicamos?',
    timestamp: '2026-04-07T09:30:00Z',
    unread: true,
  },
  {
    id: 'msg_002',
    from: 'Dr. Carlos Rodríguez',
    fromId: 'psy_001',
    preview: 'Recuerda que mañana tenemos sesión a las 3pm. ¡Nos vemos!',
    timestamp: '2026-04-06T14:00:00Z',
    unread: false,
  },
]

export const mockPlans = [
  {
    id: 'basic',
    name: 'Básico',
    price: 52,
    period: 'semana',
    description: 'Para empezar tu camino',
    features: [
      'Mensajería ilimitada con tu terapeuta',
      '1 sesión por mes (video, audio o chat)',
      'Cambio de terapeuta gratis',
      'Acceso a worksheets básicos',
      'Cancelación en cualquier momento',
    ],
    notIncluded: ['Sesiones adicionales', 'Sesiones de audio', 'Workshops grupales'],
    color: 'sage',
    popular: false,
  },
  {
    id: 'standard',
    name: 'Estándar',
    price: 72,
    period: 'semana',
    description: 'El más popular',
    features: [
      'Mensajería ilimitada con tu terapeuta',
      '1 sesión por semana (video, audio o chat)',
      'Cambio de terapeuta gratis',
      'Acceso a worksheets completos (150+)',
      'Cancelación en cualquier momento',
      'Sesiones de audio incluidas',
    ],
    notIncluded: ['Workshops grupales'],
    color: 'teal',
    popular: true,
  },
  {
    id: 'premium',
    name: 'Premium',
    price: 95,
    period: 'semana',
    description: 'Máximo apoyo',
    features: [
      'Mensajería ilimitada con tu terapeuta',
      '2 sesiones por semana (video, audio o chat)',
      'Cambio de terapeuta gratis',
      'Acceso a worksheets completos (150+)',
      'Cancelación en cualquier momento',
      'Sesiones de audio incluidas',
      'Acceso a workshops grupales mensuales',
      'Soporte prioritario 24/7',
    ],
    notIncluded: [],
    color: 'warm',
    popular: false,
  },
]

export const mockAdminStats = {
  totalUsers: 1247,
  activePatients: 834,
  verifiedTherapists: 67,
  pendingVerifications: 12,
  monthlyRevenue: 89420,
  totalSessions: 2341,
  avgRating: 4.8,
  nps: 72,
  newUsersThisMonth: 187,
  churnRate: 3.2,
  sessionCompletionRate: 91.4,
  revenueGrowth: 23.5,
}
