// Mock data for Cora platform — used in development until backend is connected
// UPDATED: Coincide con users_seed.sql
// Author: Jose Alonso Porras Ramirez

export const mockTherapists = [
  {
    id: 'psy_001',
    email: 'maria.vargas@cora.local',
    firstName: 'María Elena',
    lastName: 'Vargas Sánchez',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Maria',
    title: 'Psicóloga Clínica',
    specializations: ['Ansiedad', 'Depresión', 'Terapia Cognitivo-Conductual', 'Estrés laboral', 'Duelo'],
    languages: ['Español', 'Inglés'],
    experience: 10,
    rating: 4.92,
    reviewCount: 156,
    bio: 'Psicóloga clínica con más de 10 años de experiencia. Me especializo en terapia cognitivo-conductual para ansiedad y depresión. Mi enfoque es cálido y empático, creando un espacio seguro para que puedas explorar tus emociones. Creo firmemente que cada persona tiene los recursos para sanar y crecer.',
    license: 'CPC-2018-4521',
    verified: true,
    sessionPrice: 65,
    currency: 'USD',
    availability: {
      monday: ['09:00', '10:00', '11:00', '15:00', '16:00', '17:00'],
      tuesday: ['09:00', '10:00', '14:00', '15:00', '16:00'],
      wednesday: ['10:00', '11:00', '15:00', '16:00', '17:00'],
      thursday: ['09:00', '10:00', '11:00'],
      friday: ['14:00', '15:00', '16:00', '17:00'],
      saturday: [],
      sunday: [],
    },
    nextAvailable: '2026-04-10T09:00:00Z',
    acceptingNewPatients: true,
    sessionTypes: ['video', 'audio'],
    approach: 'Cognitivo-Conductual (TCC) y Humanista',
    education: 'Licenciatura en Psicología, UCR. Maestría en Psicología Clínica, UNA.',
  },
  {
    id: 'psy_002',
    email: 'carlos.rodriguez@cora.local',
    firstName: 'Carlos',
    lastName: 'Rodríguez Mora',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Carlos',
    title: 'Terapeuta de Pareja y Familia',
    specializations: ['Terapia de pareja', 'Terapia familiar', 'Comunicación', 'Conflictos'],
    languages: ['Español'],
    experience: 15,
    rating: 4.88,
    reviewCount: 203,
    bio: 'Terapeuta de pareja y familia con enfoque sistémico. Ayudo a parejas y familias a mejorar su comunicación, resolver conflictos y construir relaciones más saludables. Mi experiencia de 15 años me ha enseñado que todas las relaciones pueden sanar con el apoyo adecuado.',
    license: 'CPC-2015-3847',
    verified: true,
    sessionPrice: 70,
    currency: 'USD',
    availability: {
      monday: ['10:00', '11:00', '16:00', '17:00', '18:00'],
      tuesday: [],
      wednesday: ['10:00', '11:00', '16:00', '17:00', '18:00'],
      thursday: [],
      friday: ['09:00', '10:00', '11:00', '15:00', '16:00'],
      saturday: ['10:00', '11:00'],
      sunday: [],
    },
    nextAvailable: '2026-04-10T10:00:00Z',
    acceptingNewPatients: true,
    sessionTypes: ['video'],
    approach: 'Sistémico y Terapia Familiar',
    education: 'Licenciatura en Psicología, UCR. Especialización en Terapia Familiar y de Pareja, Universidad de Barcelona.',
  },
  {
    id: 'psy_003',
    email: 'ana.jimenez@cora.local',
    firstName: 'Ana Lucía',
    lastName: 'Jiménez Rojas',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ana',
    title: 'Psicóloga Infantil',
    specializations: ['Terapia infantil', 'Adolescentes', 'TDAH', 'Problemas de conducta', 'Ansiedad en niños'],
    languages: ['Español'],
    experience: 5,
    rating: 4.95,
    reviewCount: 89,
    bio: 'Psicóloga infantil especializada en terapia lúdica. Trabajo con niños y adolescentes para ayudarles a manejar sus emociones, mejorar su comportamiento y desarrollar habilidades sociales. Mi consultorio virtual está adaptado con recursos interactivos para los más pequeños.',
    license: 'CPC-2020-5892',
    verified: true,
    sessionPrice: 55,
    currency: 'USD',
    availability: {
      monday: ['14:00', '15:00', '16:00'],
      tuesday: ['09:00', '10:00', '11:00', '14:00', '15:00'],
      wednesday: ['14:00', '15:00', '16:00', '17:00'],
      thursday: ['09:00', '10:00', '11:00'],
      friday: ['14:00', '15:00', '16:00'],
      saturday: ['10:00', '11:00'],
      sunday: [],
    },
    nextAvailable: '2026-04-10T14:00:00Z',
    acceptingNewPatients: true,
    sessionTypes: ['video', 'chat'],
    approach: 'Lúdico y Cognitivo-Conductual',
    education: 'Licenciatura en Psicología, UCR. Maestría en Psicología Infantil, Universidad de Chile.',
  },
]

export const mockPatient = {
  id: 'pat_001',
  email: 'juan.perez@ejemplo.com',
  firstName: 'Juan',
  lastName: 'Pérez González',
  role: 'patient',
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Juan',
  profileComplete: true,
  createdAt: '2026-03-15T10:00:00Z',
  subscription: {
    plan: 'standard',
    status: 'active',
    price: 72,
    currency: 'USD',
    billingPeriod: 'weekly',
    nextBillingDate: '2026-04-14T00:00:00Z',
    features: ['Mensajería ilimitada', '1 sesión/semana', 'Cambio gratis de terapeuta'],
  },
  assignedTherapist: mockTherapists[0],
}

export const mockAdminUser = {
  id: 'adm_001',
  email: 'admin@cora.local',
  firstName: 'Admin',
  lastName: 'Sistema',
  role: 'admin',
  avatar: null,
  profileComplete: true,
}

export const mockTherapistUser = {
  id: 'psy_001',
  email: 'maria.vargas@cora.local',
  firstName: 'María Elena',
  lastName: 'Vargas Sánchez',
  role: 'psychologist',
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Maria',
  verified: true,
  totalPatients: 24,
  activePatients: 18,
  pendingMessages: 5,
  monthlyEarnings: 2340,
  rating: 4.92,
}

export const mockAppointments = [
  {
    id: 'apt_001',
    psychologist: mockTherapists[0],
    patient: { id: 'pat_001', firstName: 'Juan', lastName: 'Pérez' },
    scheduledAt: '2026-04-12T15:00:00Z',
    duration: 50,
    status: 'scheduled',
    type: 'video',
    roomId: 'room_future_001',
    meetingUrl: '/sesion/room_future_001',
    notes: 'Segunda sesión. Continuación del tratamiento.',
  },
  {
    id: 'apt_002',
    psychologist: mockTherapists[0],
    patient: { id: 'pat_001', firstName: 'Juan', lastName: 'Pérez' },
    scheduledAt: '2026-04-07T15:00:00Z',
    duration: 50,
    status: 'completed',
    type: 'video',
    hasReview: true,
    notes: 'Primera sesión de evaluación. El paciente presenta ansiedad generalizada.',
  },
  {
    id: 'apt_003',
    psychologist: mockTherapists[0],
    patient: { id: 'pat_001', firstName: 'Juan', lastName: 'Pérez' },
    scheduledAt: '2026-03-31T15:00:00Z',
    duration: 50,
    status: 'completed',
    type: 'video',
    hasReview: false,
  },
  {
    id: 'apt_004',
    psychologist: mockTherapists[1],
    patient: { id: 'pat_002', firstName: 'Laura', lastName: 'Sandí' },
    scheduledAt: '2026-04-10T10:00:00Z',
    duration: 50,
    status: 'scheduled',
    type: 'video',
    roomId: 'room_couple_001',
    notes: 'Sesión de pareja.',
  },
]

export const mockReviews = [
  {
    id: 'rev_001',
    psychologistId: 'psy_001',
    patient: { firstName: 'Juan', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Juan' },
    rating: 5,
    title: 'Excelente profesional',
    content: 'María Elena es increíblemente empática y profesional. Después de solo 3 sesiones ya siento una diferencia enorme en cómo manejo mi ansiedad. Lo recomiendo totalmente.',
    recommend: true,
    createdAt: '2026-04-08T10:00:00Z',
    isAnonymous: false,
  },
  {
    id: 'rev_002',
    psychologistId: 'psy_001',
    patient: { firstName: 'Carlos', avatar: null },
    rating: 5,
    title: 'Cambió mi vida',
    content: 'Llegué en un momento muy difícil y gracias al apoyo de María Elena pude salir adelante. Su metodología es clara y efectiva. Muy agradecido.',
    recommend: true,
    createdAt: '2026-04-01T15:00:00Z',
    isAnonymous: false,
  },
  {
    id: 'rev_003',
    psychologistId: 'psy_001',
    patient: { firstName: 'Usuario', avatar: null },
    rating: 4,
    title: 'Muy buena experiencia',
    content: 'La terapia online superó mis expectativas. La plataforma es fácil de usar y el terapeuta muy profesional.',
    recommend: true,
    createdAt: '2026-03-25T11:00:00Z',
    isAnonymous: true,
  },
]

export const mockPosts = [
  {
    id: 'post_001',
    author: { id: 'pat_001', firstName: 'Juan', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Juan', role: 'patient' },
    title: 'Mi primera sesión de terapia online — lo que nadie te dice',
    content: 'Cuando decidí buscar ayuda psicológica, tenía mil dudas sobre la terapia online. ¿Sería igual de efectiva? ¿Se perdería algo sin estar físicamente presente? Quiero compartir mi experiencia después de 3 meses para que otros puedan tomar una decisión informada...',
    category: 'experiences',
    tags: ['terapia-online', 'primera-vez', 'ansiedad'],
    likeCount: 47,
    commentCount: 12,
    isLiked: false,
    createdAt: '2026-04-05T10:00:00Z',
    readTime: 5,
  },
  {
    id: 'post_002',
    author: { id: 'psy_001', firstName: 'María Elena', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Maria', role: 'psychologist' },
    title: '5 técnicas de respiración para manejar ataques de ansiedad',
    content: 'La ansiedad es una de las condiciones de salud mental más comunes, y saber cómo manejarla en el momento puede marcar una gran diferencia. Hoy quiero compartirles técnicas respaldadas por la ciencia que pueden practicar en cualquier momento...',
    category: 'resources',
    tags: ['ansiedad', 'técnicas', 'respiración', 'mindfulness'],
    likeCount: 89,
    commentCount: 23,
    isLiked: true,
    createdAt: '2026-04-03T14:00:00Z',
    readTime: 7,
  },
  {
    id: 'post_003',
    author: { id: 'pat_003', firstName: 'Anónimo', avatar: null, role: 'patient' },
    title: '¿Cómo saber si necesitás terapia?',
    content: 'Muchas veces nos preguntamos si lo que estamos sintiendo "es suficientemente grave" para buscar ayuda. Quiero compartir las señales que yo ignoré por mucho tiempo antes de finalmente pedir ayuda...',
    category: 'questions',
    tags: ['salud-mental', 'autoconocimiento'],
    likeCount: 134,
    commentCount: 31,
    isLiked: false,
    createdAt: '2026-04-01T09:00:00Z',
    readTime: 4,
  },
]

export const mockPayments = [
  {
    id: 'pay_001',
    date: '2026-04-07T15:00:00Z',
    description: 'Sesión de terapia — María Elena Vargas',
    amount: 65,
    currency: 'USD',
    status: 'succeeded',
    method: 'Visa **** 4242',
  },
  {
    id: 'pay_002',
    date: '2026-03-31T15:00:00Z',
    description: 'Sesión de terapia — María Elena Vargas',
    amount: 65,
    currency: 'USD',
    status: 'succeeded',
    method: 'Visa **** 4242',
  },
  {
    id: 'pay_003',
    date: '2026-03-24T15:00:00Z',
    description: 'Sesión de terapia — María Elena Vargas',
    amount: 65,
    currency: 'USD',
    status: 'succeeded',
    method: 'Visa **** 4242',
  },
]

export const mockMessages = [
  {
    id: 'msg_001',
    from: 'María Elena Vargas',
    fromId: 'psy_001',
    preview: '¡Hola Juan! Gracias por tu confianza. Nos vemos en nuestra próxima sesión el miércoles.',
    timestamp: '2026-04-08T09:30:00Z',
    unread: true,
  },
  {
    id: 'msg_002',
    from: 'María Elena Vargas',
    fromId: 'psy_001',
    preview: 'Recuerda practicar los ejercicios de respiración que vimos. ¡Nos vemos pronto!',
    timestamp: '2026-04-07T14:00:00Z',
    unread: false,
  },
]

export const mockPlans = [
  {
    id: 'per_session',
    name: 'Por Sesión',
    price: 65,
    period: 'sesión',
    description: 'Sin compromiso',
    features: [
      'Pagás solo por las sesiones que uses',
      'Sin suscripción mensual',
      'Mensajería con tu terapeuta',
      'Cambio de terapeuta gratis',
    ],
    notIncluded: ['Sesiones ilimitadas', 'Acceso a worksheets'],
    color: 'surface',
    popular: false,
  },
  {
    id: 'basic',
    name: 'Básico',
    price: 52,
    period: 'semana',
    description: 'Para empezar tu camino',
    features: [
      'Mensajería ilimitada con tu terapeuta',
      '1 sesión por mes (video, audio o chat)',
      'Cambio de terapeuta gratis',
      'Acceso a worksheets básicos',
      'Cancelación en cualquier momento',
    ],
    notIncluded: ['Sesiones adicionales', 'Workshops grupales'],
    color: 'sage',
    popular: false,
  },
  {
    id: 'standard',
    name: 'Estándar',
    price: 72,
    period: 'semana',
    description: 'El más popular',
    features: [
      'Mensajería ilimitada con tu terapeuta',
      '1 sesión por semana (video, audio o chat)',
      'Cambio de terapeuta gratis',
      'Acceso a worksheets completos (150+)',
      'Cancelación en cualquier momento',
      'Sesiones de audio incluidas',
    ],
    notIncluded: ['Workshops grupales'],
    color: 'teal',
    popular: true,
  },
  {
    id: 'premium',
    name: 'Premium',
    price: 95,
    period: 'semana',
    description: 'Máximo apoyo',
    features: [
      'Mensajería ilimitada con tu terapeuta',
      '2 sesiones por semana (video, audio o chat)',
      'Cambio de terapeuta gratis',
      'Acceso a worksheets completos (150+)',
      'Cancelación en cualquier momento',
      'Sesiones de audio incluidas',
      'Acceso a workshops grupales mensuales',
      'Soporte prioritario 24/7',
    ],
    notIncluded: [],
    color: 'warm',
    popular: false,
  },
]

export const mockAdminStats = {
  totalUsers: 1247,
  activePatients: 834,
  verifiedTherapists: 67,
  pendingVerifications: 12,
  monthlyRevenue: 89420,
  totalSessions: 2341,
  avgRating: 4.8,
  nps: 72,
  newUsersThisMonth: 187,
  churnRate: 3.2,
  sessionCompletionRate: 91.4,
  revenueGrowth: 23.5,
}

// ============================================================
// CREDENCIALES DE PRUEBA (para desarrollo)
// ============================================================
export const TEST_CREDENTIALS = {
  admin: {
    email: 'admin@cora.local',
    password: 'Test1234!',
    role: 'admin',
    name: 'Admin Sistema',
  },
  psychologist1: {
    email: 'maria.vargas@cora.local',
    password: 'Test1234!',
    role: 'psychologist',
    name: 'María Elena Vargas Sánchez',
  },
  psychologist2: {
    email: 'carlos.rodriguez@cora.local',
    password: 'Test1234!',
    role: 'psychologist',
    name: 'Carlos Rodríguez Mora',
  },
  psychologist3: {
    email: 'ana.jimenez@cora.local',
    password: 'Test1234!',
    role: 'psychologist',
    name: 'Ana Lucía Jiménez Rojas',
  },
  patient1: {
    email: 'juan.perez@ejemplo.com',
    password: 'Test1234!',
    role: 'patient',
    name: 'Juan Pérez González',
  },
  patient2: {
    email: 'laura.sandi@ejemplo.com',
    password: 'Test1234!',
    role: 'patient',
    name: 'Laura Sandí Valverde',
  },
  patient3: {
    email: 'diego.mora@ejemplo.com',
    password: 'Test1234!',
    role: 'patient',
    name: 'Diego Mora Vargas',
  },
}